# Generated by Django 5.2.5 on 2025-10-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="lecture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="learning.lecture",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lecture",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.level",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.teacher",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="learning.assignment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="users.student",
            ),
            preserve_default=False,
        ),
    ]
