# Generated by Django 5.2.5 on 2025-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="remaining_lectures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(default="Committed", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="total_marks",
            field=models.IntegerField(default=0),
        ),
    ]
