# Generated by Django 5.2.5 on 2025-10-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
