# Generated by Django 5.2.5 on 2025-10-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lectures.lecture",
            ),
        ),
    ]
