# Generated by Django 5.2.5 on 2025-10-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_alter_assignment_lecture"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="lecture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lectures.lecture",
            ),
            preserve_default=False,
        ),
    ]
