# Generated by Django 5.2.5 on 2025-10-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_alter_assignment_lecture"),
        ("users", "0002_student_remaining_lectures_student_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
    ]
