# Generated by Django 5.2.5 on 2025-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
        ("users", "0002_student_remaining_lectures_student_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="lectures", to="users.student"
            ),
        ),
    ]
