# Generated by Django 5.2.5 on 2025-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_lecture_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
