# Generated by Django 5.2.5 on 2025-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0003_alter_lecture_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pdf",
            field=models.TextField(blank=True, null=True),
        ),
    ]
