# Generated by Django 5.2.5 on 2025-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("new_assignment", "New Assignment"),
                    ("new_lecture", "New Lecture"),
                    ("new_exam", "New Exam"),
                    ("assignment_graded", "Assignment Graded"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("lecture", "Lecture"),
                    ("exam", "Exam"),
                ],
                max_length=50,
            ),
        ),
    ]
