# Generated by Django 5.2.5 on 2025-11-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_role",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
