# Generated by Django 5.2.5 on 2025-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_recipient_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("new_assignment", "New Assignment"),
                    ("new_submission", "New Submission"),
                    ("new_lecture", "New Lecture"),
                    ("new_exam", "New Exam"),
                    ("assignment_graded", "Assignment Graded"),
                ],
                max_length=50,
            ),
        ),
    ]
